[критерий_останова]
условие = "МАКС_ВРЕМЯ"
макс_таймаут_сек = 200.0
дистанция_после_соосности_метров = 0.0

[логика_валидации]
type_проверки = "КАСКАД_УСЛОВИЙ"

  [[логика_валидации.уровни]]
  время_контроля_сек = 20.0
  ожидаемый_статус_ПО = "TRACK_CONFIRMED"
  проверять_сохранение_id = false
  примечание = "Первичная завязка трассы при входе объекта в зону барражирования"

  [[логика_валидации.уровни]]
  время_контроля_сек = 100.0
  ожидаемый_статус_ПО = "TRACK_CONFIRMED"
  проверять_сохранение_id = true
  примечание = "Цель заложила серию виражей. Проверка отсутствия численного вырождения матриц и сброса трассы"

  [[логика_валидации.уровни]]
  время_контроля_сек = 180.0
  ожидаемый_статус_ПО = "TRACK_CONFIRMED"
  проверять_сохранение_id = true
  примечание = "Длительное сопровождение на разворотах: проверка отсутствия раздувания стробов селекции"
