[критерий_останова]
условие = "МАКС_ВРЕМЯ"
макс_таймаут_сек = 60.0

[логика_валидации]
тип_проверки = "КАСКАД_УСЛОВИЙ"

  [[логика_валидации.уровни]]
  время_контроля_сек = 15.0
  ожидаемый_статус_ПО = "TRACK_FREE"
  проверять_сохранение_id = false
  примечание = "Цель выключена. Движок межинтервальной селекции обязана игнорировать шумы неба"

  [[логика_валидации.уровни]]
  время_контроля_сек = 45.0
  ожидаемый_статус_ПО = "TRACK_FREE"
  проверять_сохранение_id = false
  примечание = "Контрольная проверка на середине маршрута: отсутствие ложных автозахватов фантомных трасс"
