[мета]
ид_сценария = "0007_БАРРАЖИРОВАНИЕ_НА_ФЛАНГЕ"
интервал_времени_сек = 0.5
инициализатор_шума_seed = 1111

[[объекты_сцены]]
id = 1
тип = "ПЕЛЕНГАТОР_БЕТА"
координаты = [-400.0, 0.0, 0.0] # Пеленгатор смещен далеко на левый фланг

[[объекты_сцены]]
id = 101
тип = "ИСТРЕБИТЕЛЬ_СУ"
режим_движения = "ПО_ТОЧКАМ"
циклический_маршрут = true

[траектории]
цель_101 = "catalog/trajectories/orbit_barrage.toml"

[критерии_теста]
проверка = "catalog/validation/math_stability_check.toml"
