[мета]
ид_сценария = "0001_БАРАЖИРОВАНИЕ_БПЛА_ТРАВЕРЗ"
интервал_времени_сек = 0.5
инициализатор_шума_seed = 1337

[[объекты_сцены]]
id = 1
тип = "ПЕЛЕНГАТОР_АЛЬФА"
координаты = [0.0, 0.0, 0.0]

[[объекты_сцены]]
id = 101
тип = "БПЛА_МАЛАЯ_ЭПР"
режим_движения = "ПО_ТОЧКАМ"
циклический_маршрут = true

[траектории]
цель_101 = "catalog/trajectories/arc_route_900.toml"

[критерии_теста]
проверка = "catalog/validation/retro_memory_check.toml"
