[мета]
ид_сценария = "0002_ИСТРЕБИТЕЛЬ_СКОРОСТНОЙ_ТРАНЗИТ"
интервал_времени_сек = 0.2 # Повышенная дискретность для высокой скорости
инициализатор_шума_seed = 2026

[[объекты_сцены]]
id = 1
тип = "РЛС_СТАЦИОНАРНАЯ"
координаты = [0.0, 0.0, 0.0]

[[объекты_сцены]]
id = 101
тип = "ТЯЖЕЛЫЙ_ИСТРЕБИТЕЛЬ"
режим_движения = "ПО_ТОЧКАМ"
циклический_маршрут = false

[траектории]
цель_101 = "catalog/trajectories/straight_echelon_100.toml"

[критерии_теста]
проверка = "catalog/validation/math_stability_check.toml"
