[мета]
ид_сценария = "0004_ФИЛЬТРАЦИЯ_ФАНТОМОВ_ТИШИНА"
интервал_времени_сек = 0.5
инициализатор_шума_seed = 9999

[[объекты_сцены]]
id = 1
тип = "РЛС_ГЛАВНАЯ"
координаты = [0.0, 0.0, 0.0]

[[объекты_сцены]]
id = 101
тип = "ЦЕЛЬ_В_РЕЖИМЕ_МОЛЧАНИЯ"
режим_движения = "ПО_ТОЧКАМ"
циклический_маршрут = false

[траектории]
цель_101 = "catalog/trajectories/straight_echelon_100.toml"

[критерии_теста]
проверка = "catalog/validation/strict_false_check.toml"
