[мета]
ид_сценария = "0006_СЕЛЕКЦИЯ_ПРИ_КРИТ_ШУМЕ"
интервал_времени_сек = 0.5
инициализатор_шума_seed = 4242 # Измененный сид для генерации жестких выбросов шума

[[объекты_сцены]]
id = 1
тип = "РЛС_СТАЦИОНАРНАЯ"
координаты = [0.0, 0.0, 0.0]

[[объекты_сцены]]
id = 101
тип = "ТЯЖЕЛЫЙ_ИСТРЕБИТЕЛЬ"
режим_движения = "ПО_ТОЧКАМ"
циклический_маршрут = false

[траектории]
цель_101 = "catalog/trajectories/straight_echelon_100.toml"

[критерии_теста]
проверка = "catalog/validation/math_stability_check.toml"
